# Generated by Django 5.0.4 on 2024-04-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_peertopeer'),
    ]

    operations = [
        migrations.AddField(
            model_name='peertopeer',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
